### ISSUE TITLE
Feedback for button not working

### ISSUE THREAD

**Issue by blockiyt** [bitfocus/companion-module-techministry-midirelay#15]
Hey, I am trying to use the color change for the buttons but it seems that it doesn't work.
I selected the correct MIDI port, and also monitored the port via a program, to check if the messages are coming thru, and yes they do. 
I also selected the correct type, channel, note and velocity, but the background does not change.
I would be glad, if you could help!
Thank you.

**Comment by josephdadams** [comment]
Do the module variables show that midi data is being received?

**Comment by blockiyt** [comment]
Yes, they do.

**Comment by josephdadams** [comment]
What kind of midi data is it? noteon, what channel, etc.

**Comment by blockiyt** [comment]
It‘s a Note on on Channel 1 with A0 and Velocity 0 or 127

**Comment by rmk36** [comment]
For sake of bringing the bringing the conversation together into one place, I am having a similar issue involving midi data note working correctly for companion triggers.    I originally posted this video [here](https://www.facebook.com/1435410062/videos/1072755730641034/)

I'm running Companion 3.2.0 and midi-relay 3.3.0 both on the same  Windows 11 PC.

I can run triggers based on an incoming midi message, but cannot use the midi data as a condition to discern with channel/note was pressed.

https://github.com/bitfocus/companion-module-techministry-midirelay/assets/152319647/cc1fcdbc-a4fe-4a34-9354-4c3f3f86c593

**Comment by josephdadams** [comment]
I just fixed this in the module version `v3.1.1` and am pushing it to betas now. builds run every 6 hours or you can download the module code yourself
