### ISSUE TITLE
Missing "0" in value slider

### ISSUE THREAD

**Issue by mko1989** [bitfocus/companion-module-techministry-midirelay#2]
Hello,
I'm trying to send Control Change messages and there is no way to send 0 value which is needed. Hope companion allowes zero.

**Comment by josephdadams** [comment]
@mko1989 I can add it. I’ll update you when I have done it.

**Comment by josephdadams** [comment]
It's done in the code, I'll ask @JeffreyDavidsz to update the core with the latest code and fire off a build.
