### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tap-chris** [bitfocus/companion-module-techministry-midirelay#4]
```
platform=win32
arch=x64
electron=2.0.18
companion=2.0.0 (3505d55-2201)
```

If I start companion with the midi-relay instance enabled but the midi-relay not started and then access the admin interface I get a `Maximum call stack size exceeded` error. If I disable the instance or start the midi-relay, the error disappears. 

This only happens if I start companion with electron. If I start the same build in headless mode the error doesn't show. I tested this with other modules but didn't get an error.

I don't know if this is specific to the midi-relay module but so far I'm only getting the error here.

![Error Message](https://user-images.githubusercontent.com/11670622/76252318-d3467980-6248-11ea-8d73-4a861270df65.png)

**Comment by josephdadams** [comment]
@tap-chris I've made some improvements. Can you pull the latest into your development environment and test it for me? Specifically, close out the midi-relay server and it should handle the error much more gracefully.

**Comment by tap-chris** [comment]
@josephdadams I'll pull and test this evening. I let you know, thanks ;)

**Comment by tap-chris** [comment]
I've tested it headless and build and the error is gone.
If I start the relay after companion it doesn't see that it is now available but this is the nature of the protocol I guess and totally fine with me. As soon as I fire an action it jumps back to OK.
Vise versa the same if I close it and fire an action it detects that it's gone and switches the status.
The only thing I can see is that if I enable the instance it jumps to OK and then goes to ERROR once it sees there is a problem. Dunno if it is much work to show something like Connecting... while it tries the first time but I don't mind if it would be too much work. Just as a note.
Thanks for your work.

**Comment by josephdadams** [comment]
I will remove the false OK states which are really just as the module inits. How about I add an interval to do a status check of the server every 60 seconds?

**Comment by tap-chris** [comment]
Would certainly be nice to tell the user that something is wrong in case the relay dies before, like in my case, a cue is called and nothing is starting :) It never happened but certainly gives confidence.
I like the idea, thanks!

**Comment by josephdadams** [comment]
I implemented response control of the server API so that now in the log you should get a visual representation of whether or not your MIDI messages were actually sent. I have decided not to implement the heartbeat function at this time but we can always revisit that! I'd rather implement a watchdog on the server side than to have a bunch of clients pinging the server for status.
