### ISSUE TITLE
[BUG] MIDI note turns off automatically after 10 minutes. [midi-relay]

### ISSUE THREAD

**Issue by kwonsangjun** [bitfocus/companion-module-techministry-midirelay#6]
I am controlling the stage lighting using a midi-relay module in the streamdeck and companion. But when I turn on the light by sending a MIDI signal, the MIDI note turn off automatically after exactly 10 minutes. The same symptoms appear in the MIDI of the StreamDeck basic app. Which part has the function to turn off after 10 minutes?

RTP midi interface : iconnectivity mioXM
Stage Lighting : Work pro Stage 4824 DMX

**Comment by josephdadams** [comment]
If it happens with the Streamdeck basic app, I would say that shows it is not a midi-relay problem, but something on the end device. So I will close this since it is not a midi relay problem.

**Comment by kwonsangjun** [comment]
its basic function in Work pro Stage 4824 DMX 

--------------------------
"During receiving and sending MIDI data, all MIDI scenes and channels being run
  will automatically paused if there is no response within 10 minutes."
--------------------------
