### ISSUE TITLE
Idea/ Feature Request

### ISSUE THREAD

**Issue by TreborKutscher** [bitfocus/companion-module-techministry-midirelay#7]
I would apprecita the ability of companion to ingest midi tempo data and than make this an trigger with an additional multiplicator so you can fire a button after x beats.

also a musical timframe ith 3/4 or 4/4 per bar might be handy as  an additional input so you dont have to calcultat in miliseconds.

**Comment by josephdadams** [comment]
I would say this is a feature request for the primary midi-relay program, not necessarily the Companion module that interacts with it. https://github.com/josephdadams/midi-relay

That said, I don't know if I will have time to get to implement something like this. There might be better software out there that can do the listening to midi better than midi-relay, which was really mostly designed to send midi, not receive.
