### ISSUE TITLE
Pass companion variables to  velocity parameter - feature request

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion-module-techministry-midirelay#9]
I have lights (ADJ) that are controlled via MIDI. I'd like to use Companion to raise or lower or recall a discrete value (e.g. intensity, color) into a variable. 
The change in that variable's value would then effect a trigger, which would then send a MIDI function using that variable's value as a velocity in the Note On MIDI sequence. This is what makes my lights change their intensity or color. 

Presently in order to accomplish this I believe I'd have to create, per MIDI note, 128 different triggers to send any of the possible values.

P.S. it might be nice to also be able to pass Companion variables into the other "Note On" and "Note Off" parameters or in other places on other MIDI functions. I don't particularly need this but it's not all about me ;-)

**Comment by josephdadams** [comment]
You can use variables for the various fields in the new v3.0.0 of the module. It does require using the new v3.0.0 of midi-relay to be compatible with the new version of the module. It is a free download.
